version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=changeme123"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
    networks:
      - elastic
    restart: unless-stopped

networks:
  elastic:
    driver: bridge
