paths:
  model:
    dir: "models/embeddings"
    file: "stella_v5"

model:
  download_url: "dunzhang/stella_en_1.5B_v5"
  max_length: 512
  batch_size: 32
  device: "auto" # auto, cuda, cpu
  trust_remote_code: True
