paths:
  model:
    dir: "models/rerank"
    file: "gte-qwen2"

model:
  download_url: "Alibaba-NLP/gte-Qwen2-7B-instruct"
  batch_size: 32
  device: "auto"
  max_length: 2048
  trust_remote_code: True
